on: [push, pull_request]
name: quickSubmit
jobs:
  quickSubmit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - application: ojs
            php-version: 8.3
            database: mysql
          - application: ojs
            php-version: 8.2
            database: mysql
          - application: ojs
            php-version: 8.3
            database: pgsql
          - application: ojs
            php-version: 8.2
            database: pgsql
    name: quickSubmit
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
         node_version: 20
         branch: main
         repository: pkp
         plugin: true
         dataset_inject: true
